const ACTIVE_BOOKING_STATUSES = ['PENDING', 'DEPOSIT_PAID'];

const ACTIVE_CONTRACT_STATUSES = [
  'DRAFT',
  'PENDING_CUSTOMER_SIGNATURE',
  'PENDING_MANAGER_SIGNATURE',
  'ACTIVE',
  'EXPIRING_SOON',
];

module.exports = { ACTIVE_BOOKING_STATUSES, ACTIVE_CONTRACT_STATUSES };
